name: Run tests

on:
  pull_request:
    branches: [main, working-branch]
  push:
    branches: [main, working-branch]

jobs:
  Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Run tests (Node.js ${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Add server .env file.
        run: |
          (echo ${{ secrets.PORT }} 
          echo ${{ secrets.MONGODB_URL }} 
          echo ${{ secrets.MONGODB_URL_TEST }}
          echo ${{ secrets.SALT_ROUNDS }}
          echo ${{ secrets.SECRET }}) > .env

        working-directory: ./backend
      - name: Install Server dependencies
        run: npm ci
        working-directory: ./backend
      - name: Run Backend Tests
        run: npm run test
        working-directory: ./backend
