name: Run tests

on:
  pull_request:
    branches: [main, working-branch]
  push:
    branches: [main, working-branch]

env:
  ENV_FILE: ${{ secrets.ENV_FILE}}

jobs:
  Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Run tests (Node.js ${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Add server .env file.
        run: echo "$ENV_FILE" > .env
        working-directory: ./backend
      - name: Install Server dependencies
        run: npm ci
        working-directory: ./backend
      - name: Run Backend Tests
        run: npm run test
        working-directory: ./backend
